src.echo.train:
  source_model_name: eugenesiow/bart-paraphrase
  similarity_evaluator_name: flax-sentence-embeddings/all_datasets_v4_MiniLM-L6
  value_model_name: bert-base-uncased
  train_split_path: data/sst2/train.csv
  eval_split_path: data/sst2/validation.csv
  max_len: 16
  batch_size: 1
  n_epochs: 4
  attacker_lr: 1e-5
  value_lr: 1e-4
  save_dir: runs/echo/
  n_max_train_batches: 1024
  call_parameters_save_path: runs/echo/log.txt

src.echo.train_dpo:
  source_model_name: eugenesiow/bart-paraphrase
  similarity_evaluator_name: flax-sentence-embeddings/all_datasets_v4_MiniLM-L6
  train_split_path: data/sst2/train.csv
  eval_split_path: data/sst2/validation.csv
  max_len: 16
  batch_size: 1
  n_epochs: 4
  attacker_lr: 1e-5
  beta: 0.1
  temperature: 1
  save_dir: runs/echo/
  n_max_train_samples: 1024
  general_training_log_path: runs/echo/log.txt

src.experimental_generators.unidirectional.train_dpo:
  source_model_name: eugenesiow/bart-paraphrase
  source_model_weights_path: null
  gan_discriminator_weights_path: null
  train_split_path: data/sst2/train.csv
  eval_split_path: data/sst2/validation.csv
  target_label_name: negative
  max_len: 16
  batch_size: 1
  n_epochs: 4
  attacker_lr: 1e-5
  gan_lr: 1e-4
  beta: 0.1
  temperature: 1
  gan_weight_decay: 5e-07
  save_dir: runs/unidirectional/
  n_max_train_samples: 1024
  general_training_log_path: runs/unidirectional/log.txt
